european_countries = ["France", "Germany", "Italy", "Spain", "United Kingdom",
                       "Netherlands", "Sweden", "Portugal", "Greece", "Poland"]

cities_dict = {
    "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Bordeaux", "Lille", "Rennes"],
    "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig"],
    "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania"],
    "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Las Palmas", "Bilbao"],
    "United Kingdom": ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Bristol", "Edinburgh", "Leeds", "Sheffield", "Newcastle"],
    "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen"],
    "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping"],
    "Portugal": ["Lisbon", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Funchal", "Coimbra", "Setúbal", "Queluz", "Aveiro"],
    "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Rhodes", "Ioannina", "Chania", "Chalcis"],
    "Poland": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice"]
}

european_countries_check = [
    "Albania", "Andorra", "Austria", "Belarus", "Belgium", "Bosnia and Herzegovina",
    "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland",
    "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Kosovo",
    "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco",
    "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal", "Romania",
    "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland",
    "Turkey", "Ukraine", "United Kingdom", "Vatican City"
]

city_ceck = {
    "Albania": ["Tirana", "Durres", "Vlore", "Shkoder", "Berat", "Korce", "Fier", "Elbasan", "Pogradec", "Sarande"],
    "Andorra": ["Andorre-la-Vieille", "Les Escaldes", "Encamp", "La Massana", "Canillo", "Ordino", "Sant Julia de Loria", "Pas de la Casa", "Soldeu", "Arinsal"],
    "Austria": ["Vien", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Wels", "Villach", "Sankt Pölten", "Dornbirn"],
    "Belarus": ["Minsk", "Brest", "Grodno", "Mogilev", "Gomel", "Vitebsk", "Bobruisk", "Baranovichi", "Borisov", "Pinsk"],
    "Belgium": ["Bruxelles", "Anvers", "Gand", "Charleroi", "Liège", "Bruges", "Namur", "Louvain", "Mons", "Courtrai"],
    "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bihac", "Prijedor", "Brcko", "Doboj", "Cazin"],
    "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven", "Dobrich", "Shumen"],
    "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula", "Karlovac", "Sisak", "Varazdin"],
    "Cyprus": ["Nicosie", "Limassol", "Larnaca", "Paphos", "Famagouste", "Kyrenia", "Protaras", "Paralimni", "Lefkara", "Ayia Napa"],
    "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec", "Olomouc", "Ceske Budejovice", "Hradec Kralove", "Pardubice", "Zlin"],
    "Denmark": ["Copenhague", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde"],
    "Estonia": ["Tallinn", "Tartu", "Narva", "Parnu", "Kohtla-Jarve", "Viljandi", "Rakvere", "Maardu", "Sillamae", "Kuressaare"],
    "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyvaskyla", "Lahti", "Kuopio", "Pori"],
    "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"],
    "Germany": ["Berlin", "Hambourg", "Munich", "Cologne", "Francfort", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig"],
    "Greece": ["Athènes", "Thessalonique", "Patras", "Héraklion", "Larissa", "Volos", "Rhodes", "Ioannina", "Chania", "Chalcis"],
    "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs", "Gyor", "Nyíregyháza", "Kecskemet", "Szekesfehervar", "Szombathely"],
    "Iceland": ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Akureyri", "Reykjanesbær", "Keflavik", "Selfoss", "Akranes", "Vestmannaeyjar", "Isafjordur"],
    "Ireland": ["Dublin", "Cork", "Galway", "Limerick", "Waterford", "Drogheda", "Dundalk", "Sligo", "Wexford", "Kilkenny"],
    "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania"],
    "Kosovo": ["Pristina", "Prizren", "Peja", "Gjakova", "Mitrovica", "Ferizaj", "Gjilan", "Vushtrri", "Suhareka", "Podujeva"],
    "Latvia": ["Riga", "Daugavpils", "Liepaja", "Jelgava", "Jurmala", "Ventspils", "Rezekne", "Valmiera", "Ogre", "Cesis"],
    "Liechtenstein": ["Vaduz", "Schaan", "Triesen", "Balzers", "Eschen", "Mauren", "Ruggell", "Gamprin", "Schellenberg", "Planken"],
    "Lithuania": ["Vilnius", "Kaunas", "Klaipeda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė", "Mažeikiai", "Jonava", "Utena"],
    "Luxembourg": ["Luxembourg-Ville", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck", "Diekirch", "Wiltz", "Echternach", "Rumelange", "Grevenmacher"],
    "Malta": ["La Valette", "Birkirkara", "Mosta", "Qormi", "Zabbar", "San Pawl il-Bahar", "Zejtun", "Sliema", "Zurrieq", "Rabat"],
    "Moldova": ["Chisinau", "Tiraspol", "Balti", "Bender", "Cahul", "Comrat", "Soroca", "Orhei", "Ungheni", "Straseni"],
    "Monaco": ["Monaco-Ville", "Monte-Carlo", "La Condamine", "Fontvieille", "Les Moneghetti", "Larvotto", "Saint-Roman", "La Rousse", "Jardin Exotique", "Moneghetti"],
    "Montenegro": ["Podgorica", "Nikšić", "Pljevlja", "Herceg Novi", "Bar", "Budva", "Kotor", "Tivat", "Cetinje", "Ulcinj"],
    "Netherlands": ["Amsterdam", "Rotterdam", "La Haye", "Utrecht", "Eindhoven", "Tilburg", "Groningue", "Almere", "Breda", "Nijmegen"],
    "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles", "Ohrid", "Gostivar", "Strumica", "Kavadarci"],
    "Norway": ["Oslo", "Bergen", "Stavanger", "Trondheim", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromsø", "Sarpsborg"],
    "Poland": ["Varsovie", "Cracovie", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice"],
    "Portugal": ["Lisbonne", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Setúbal", "Coimbra", "Funchal", "Almada", "Aveiro"],
    "Romania": ["Bucarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov", "Galați", "Ploiești", "Oradea"],
    "Russia": ["Moscou", "Saint-Pétersbourg", "Novossibirsk", "Iekaterinbourg", "Nijni Novgorod", "Kazan", "Tcheliabinsk", "Omsk", "Samara", "Rostov-sur-le-Don"],
    "San Marino": ["Saint-Marin", "Serravalle", "Borgo Maggiore", "Domagnano", "Faetano", "Fiorentino", "Montegiardino", "Città di San Marino"],
    "Serbia": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Čačak", "Subotica", "Zrenjanin", "Pančevo", "Kraljevo", "Smederevo"],
    "Slovakia": ["Bratislava", "Košice", "Prešov", "Žilina", "Banská Bystrica", "Nitra", "Trnava", "Trenčín", "Martin", "Poprad"],
    "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Ptuj", "Trbovlje", "Kamnik"],
    "Spain": ["Madrid", "Barcelone", "Valence", "Séville", "Bilbao", "Málaga", "Murcie", "Palma", "Valladolid", "Cordoue"],
    "Sweden": ["Stockholm", "Göteborg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping"],
    "Switzerland": ["Zurich", "Genève", "Bâle", "Lausanne", "Berne", "Winterthour", "Lucerne", "Saint-Gall", "Lugano", "Bienne"],
    "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana", "Antalya", "Konya", "Gaziantep", "Mersin", "Diyarbakır"],
    "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol"],
    "United Kingdom": ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Edinburgh", "Leeds", "Bristol", "Sheffield", "Newcastle upon Tyne"],
    "Vatican City": ["Vatican City"]
}
